"""Domain models for Phase 9: Fleet Guardian -- Real-Time Streaming.

Models: GPSPing, TemperatureReading, FleetAlert, FleetMemoryEntry.

GPSPing and TemperatureReading represent raw telemetry events from Kafka.
FleetAlert is the output of the anomaly detector.
FleetMemoryEntry stores cross-session patterns for agent memory.
"""

from datetime import datetime
from decimal import Decimal
from enum import StrEnum

from pydantic import BaseModel, Field


class AlertType(StrEnum):
    """Types of anomalies the fleet guardian can detect."""

    TEMPERATURE_SPIKE = "temperature_spike"
    TEMPERATURE_DRIFT = "temperature_drift"
    GPS_DEVIATION = "gps_deviation"
    SPEED_ANOMALY = "speed_anomaly"
    HEARTBEAT_TIMEOUT = "heartbeat_timeout"


class AlertSeverity(StrEnum):
    """Alert severity levels for priority queueing."""

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class GPSPing(BaseModel):
    """Raw GPS telemetry event from a truck.

    Consumed from Kafka topic: fleet.gps-pings.
    """

    truck_id: str = Field(min_length=1)
    latitude: float = Field(ge=-90.0, le=90.0)
    longitude: float = Field(ge=-180.0, le=180.0)
    speed_kmh: float = Field(ge=0.0)
    heading: float = Field(ge=0.0, le=360.0)
    timestamp: datetime
    engine_on: bool = True


class TemperatureReading(BaseModel):
    """Temperature sensor reading from a refrigerated truck.

    Consumed from Kafka topic: fleet.temperature.
    Sensor range: -100C to 100C (hardware limits).
    """

    truck_id: str = Field(min_length=1)
    sensor_id: str = Field(min_length=1)
    temp_celsius: float = Field(ge=-100.0, le=100.0)
    setpoint_celsius: float
    timestamp: datetime


class FleetAlert(BaseModel):
    """Alert generated by the anomaly detector.

    Published to Kafka topic: fleet.alerts.
    Triggers the LangGraph Fleet Response agent.
    """

    alert_id: str = Field(min_length=1)
    truck_id: str = Field(min_length=1)
    alert_type: AlertType
    severity: AlertSeverity
    details: str
    timestamp: datetime
    resolved: bool = False
    cargo_value_eur: Decimal | None = None


class FleetMemoryEntry(BaseModel):
    """Cross-session agent memory entry.

    Stored in PostgreSQL (long-term) or serialized to Redis (medium-term).
    Enables pattern detection across multiple anomaly investigations.
    """

    memory_id: str | None = None
    truck_id: str = Field(min_length=1)
    pattern: str = Field(min_length=1)
    alert_type: str
    action_taken: str
    outcome: str
    learned_at: datetime
    occurrence_count: int = 1
